# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conta_receber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_vencimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('1', 'Em Aberto'), ('2', 'Paga')], max_length=1)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
