# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='caixa_geral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_op', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao_op', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('op', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], max_length=1)),
            ],
        ),
    ]
