# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_delete_conta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caixa_geral',
        ),
    ]
