# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_delete_caixa_geral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
